default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: city-wave-server_development

test:
  <<: *default
  database: city-wave-server_test

production:
  <<: *default
  database: city-wave-server_production
